

server:
  error:
    include-message: always
    
  port: 9001
  
  
  
spring:

  application:
    name: TRANSACTION-SERVICE 

  datasource:
    url: jdbc:mysql://localhost:3306/database_name        #specify the database_name
    username:                                             #mysql username
    password:                                             #mysql password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
 
  
  
eureka:
  client:
    register-with-eureka: true        
    fetch-registry: true
    
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
  instance:
    hostname: localhost 
